# These are supported funding model platforms

github: [quaresma870]
# open_collective: perchtail       # uncomment once/if set up
# ko_fi: quaresma870               # uncomment once/if set up
# custom: ["https://example.com/donate"]
