"""add mfa fields to user and mfa_backup_code table

Revision ID: 6ba4603526f4
Revises: a1c3f6e4b2d7
Create Date: 2026-09-24 22:16:58.226028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ba4603526f4'
down_revision: Union[str, Sequence[str], None] = 'a1c3f6e4b2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_backup_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_backup_code_user_id'), 'mfa_backup_code', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping the search_index_fts* virtual
    # tables here -- those are raw-SQL FTS5 tables created by
    # app/db.py's ensure_search_schema, not part of SQLModel.metadata, so
    # autogenerate always sees them as "unknown" and wants to drop them.
    # Removed from this migration by hand; do the same for any future one.
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user', sa.Column('mfa_secret_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('mfa_enrolled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('mfa_last_used_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mfa_last_used_step')
    op.drop_column('user', 'mfa_enrolled_at')
    op.drop_column('user', 'mfa_secret_encrypted')
    op.drop_column('user', 'mfa_enabled')
    op.drop_index(op.f('ix_mfa_backup_code_user_id'), table_name='mfa_backup_code')
    op.drop_table('mfa_backup_code')
    # ### end Alembic commands ###
