"""add search index state and source.search_indexing_enabled

Revision ID: 8ff0150df75b
Revises: 91b76f75d422
Create Date: 2026-07-30 06:37:25.596280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ff0150df75b'
down_revision: Union[str, Sequence[str], None] = '91b76f75d422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'file_path', name='uq_search_index_state_source_path')
    )
    # server_default needed so this NOT NULL column can be added to a
    # non-empty `source` table under SQLite; the model-level `= False`
    # default only applies to rows created after this migration runs.
    op.add_column(
        'source',
        sa.Column(
            'search_indexing_enabled', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # FTS5 virtual table for the search index itself — not representable as
    # a SQLModel/SQLAlchemy table, so it's raw SQL here (mirrors
    # app.db.ensure_search_schema, which (re)creates this idempotently at
    # app startup too, in case a deployment's DB was provisioned some other
    # way than running this migration).
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS search_index_fts "
        "USING fts5(source_id UNINDEXED, file_path UNINDEXED, "
        "line_number UNINDEXED, snippet)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS search_index_fts")
    op.drop_column('source', 'search_indexing_enabled')
    op.drop_table('search_index_state')
    # ### end Alembic commands ###
