"""add agent protocol fields to source

Revision ID: 91b76f75d422
Revises: da170b46a77c
Create Date: 2026-07-29 23:06:06.579439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91b76f75d422'
down_revision: Union[str, Sequence[str], None] = 'da170b46a77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('agent_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('agent_last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'agent_last_seen_at')
    op.drop_column('source', 'agent_token_hash')
    # ### end Alembic commands ###
