"""add folder model and source.folder_id

Revision ID: da170b46a77c
Revises: bb83693215c2
Create Date: 2026-07-29 13:18:39.891589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da170b46a77c'
down_revision: Union[str, Sequence[str], None] = 'bb83693215c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite can't ALTER TABLE to add a FK constraint directly — batch mode
    # does the copy-and-move dance needed to add both the column and the
    # constraint together.
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_source_folder_id_folder', 'folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint('fk_source_folder_id_folder', type_='foreignkey')
        batch_op.drop_column('folder_id')
    op.drop_table('folder')
    # ### end Alembic commands ###
